---
triple:          'arm64-apple-darwin'
binary-path:     .welcome.out
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _make_it_higher, symObjAddr: 0x0, symBinAddr: 0x100003F1C, symSize: 0x20 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _make_it_higher, symObjAddr: 0x0, symBinAddr: 0x100003F1C, symSize: 0x20 }
  - { offsetInCU: 0x69, offset: 0x69, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x20, symBinAddr: 0x100003F3C, symSize: 0x44 }
...
